# Generated by Django 4.2.27 on 2026-01-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_vegetariano', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_fabricacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('PRO', 'Promoción'), ('PRG', 'Programada'), ('CAN', 'Cancelada')], default='DIS', max_length=3)),
                ('toppings', models.ManyToManyField(to='app.topping')),
            ],
        ),
    ]
