# Generated by Django 4.2.27 on 2026-01-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
